### ISSUE TITLE
Version Conflicts in environment.yml Prevent Environment Setup

### ISSUE THREAD

**Issue by TT2TER** [JiangkaiWu/Promptus#1]
There are version conflicts in the provided environment.yml file, making it impossible to set up the environment. This seems to be caused by dependency compatibility issues.

Steps to Reproduce
	1.	Clone the repository.
	2.	Run conda env create -f environment.yml.
	3.	Observe the version conflict errors during environment creation.

Suggested Solution

Please provide a list of key environment specifications, including:
	•	Python version
	•	PyTorch version
	•	Versions of essential libraries (e.g., transformers, diffusers, etc.)

This will help users manually configure the environment and avoid these issues.

Environment Details
	•	OS: Ubuntu 20.04
	•	GPU: NVIDIA 4090

Looking forward to your guidance on this issue.

**Comment by JiangkaiWu** [comment]
Hi @TT2TER ,

Thank you for the suggestions! I updated the environment.yml and also provided manual installation commands for each package, specifying the exact versions. I set up a new environment from scratch on my machine and successfully replicated it. I hope this is useful to you.

**Comment by TT2TER** [comment]
> Hi @TT2TER ,  你好 ，
> 
> Thank you for the suggestions! I updated the environment.yml and also provided manual installation commands for each package, specifying the exact versions. I set up a new environment from scratch on my machine and successfully replicated it. I hope this is useful to you.谢谢您的建议！我更新了environment.yml，并为每个包提供了手动安装命令，指定了确切的版本。我在我的机器上从头开始设置了一个新环境并成功复制了它。我希望这对你有用。

It works！Wish you all the best in your work and life!
